from tkinter import *
import random
import os

def buildWindow():
    window = Tk()
    window.title("Speak to God")
    window.geometry("900x175")

    lblGodSays = Label(window, text="God says:", font="10")
    lblGodSays.grid(column=0, row=0)
    lblWord0 = Label(window, text=word0)
    lblWord0.grid(column=1, row=0)
    lblWord1 = Label(window, text=word1)
    lblWord1.grid(column=2, row=0)
    lblWord2 = Label(window, text=word2)
    lblWord2.grid(column=3, row=0)
    lblWord3 = Label(window, text=word3)
    lblWord3.grid(column=4, row=0)
    lblWord4 = Label(window, text=word4)
    lblWord4.grid(column=5, row=0)
    lblWord5 = Label(window, text=word5)
    lblWord5.grid(column=6, row=0)
    lblWord6 = Label(window, text=word6)
    lblWord6.grid(column=7, row=0)
    lblWord7 = Label(window, text=word7)
    lblWord7.grid(column=0, row=1)
    lblWord8 = Label(window, text=word8)
    lblWord8.grid(column=1, row=1)
    lblWord9 = Label(window, text=word9)
    lblWord9.grid(column=2, row=1)
    lblWord10 = Label(window, text=word10)
    lblWord10.grid(column=3, row=1)
    lblWord11 = Label(window, text=word11)
    lblWord11.grid(column=4, row=1)
    lblWord12 = Label(window, text=word12)
    lblWord12.grid(column=5, row=1)
    lblWord13 = Label(window, text=word13)
    lblWord13.grid(column=6, row=1)
    lblWord14 = Label(window, text=word14)
    lblWord14.grid(column=7, row=1)
    lblWord15 = Label(window, text=word15)
    lblWord15.grid(column=0, row=2)
    lblWord16 = Label(window, text=word16)
    lblWord16.grid(column=1, row=2)
    lblWord17 = Label(window, text=word17)
    lblWord17.grid(column=2, row=2)
    lblWord18 = Label(window, text=word18)
    lblWord18.grid(column=3, row=2)
    lblWord19 = Label(window, text=word19)
    lblWord19.grid(column=4, row=2)
    lblWord20 = Label(window, text=word20)
    lblWord20.grid(column=5, row=2)
    lblWord21 = Label(window, text=word21)
    lblWord21.grid(column=6, row=2)
    lblWord22 = Label(window, text=word22)
    lblWord22.grid(column=7, row=2)
    lblWord23 = Label(window, text=word23)
    lblWord23.grid(column=0, row=3)
    lblWord24 = Label(window, text=word24)
    lblWord24.grid(column=1, row=3)
    lblWord25 = Label(window, text=word25)
    lblWord25.grid(column=2, row=3)
    lblWord26 = Label(window, text=word26)
    lblWord26.grid(column=3, row=3)
    lblWord27 = Label(window, text=word27)
    lblWord27.grid(column=4, row=3)
    lblWord28 = Label(window, text=word28)
    lblWord28.grid(column=5, row=3)
    lblWord29 = Label(window, text=word29)
    lblWord29.grid(column=6, row=3)
    lblWord30 = Label(window, text=word30)
    lblWord30.grid(column=7, row=3)
    lblWord31 = Label(window, text=word31)
    lblWord31.grid(column=0, row=4)
    lblWord32 = Label(window, text=".")
    lblWord32.grid(column=1, row=4)

    btnNew = Button(window, text="Generate Answer", command=restartProgram)
    btnNew.grid(column=3, row=99)
    btnExit = Button(window, text="Exit", command=exit)
    btnExit.grid(column=3, row=100)

    window.mainloop()

def openDict():
    global godWords
    with open('english.txt') as f:
        godWords = f.read().splitlines()

def findWords():
    global word0, word1, word2, word3, word4, word5, word6, word7, word8, word9, word10, word11, word12, word13, word14, word15, word16, word17, word18, word19, word20, word21, word22, word23, word24, word25, word26, word27, word28, word29, word30, word31
    # Variables (symbolic to 32 random 32bit strings)
    word0 = random.choice(godWords)
    word1 = random.choice(godWords)
    word2 = random.choice(godWords)
    word3 = random.choice(godWords)
    word4 = random.choice(godWords)
    word5 = random.choice(godWords)
    word6 = random.choice(godWords)
    word7 = random.choice(godWords)
    word8 = random.choice(godWords)
    word9 = random.choice(godWords)
    word10 = random.choice(godWords)
    word11 = random.choice(godWords)
    word12 = random.choice(godWords)
    word13 = random.choice(godWords)
    word14 = random.choice(godWords)
    word15 = random.choice(godWords)
    word16 = random.choice(godWords)
    word17 = random.choice(godWords)
    word18 = random.choice(godWords)
    word19 = random.choice(godWords)
    word20 = random.choice(godWords)
    word21 = random.choice(godWords)
    word22 = random.choice(godWords)
    word23 = random.choice(godWords)
    word24 = random.choice(godWords)
    word25 = random.choice(godWords)
    word26 = random.choice(godWords)
    word27 = random.choice(godWords)
    word28 = random.choice(godWords)
    word29 = random.choice(godWords)
    word30 = random.choice(godWords)
    word31 = random.choice(godWords)

def restartProgram():
    os.execl(sys.executable, sys.executable, *sys.argv)

def exit():
    quit()

def main():
    openDict()
    findWords()
    buildWindow()

main()
